### ISSUE TITLE
fails newest zig master

### ISSUE THREAD

**Issue by markfirmware** [fengb/fundude#57]
https://github.com/markfirmware/fundude/runs/759432331?check_suite_focus=true

I don't think there is yet a gh action that will trigger automatically when zig master is updated.

**Comment by fengb** [comment]
Ah,  I this was "fixed" this via https://github.com/fengb/fundude/commit/f28bc93a19394482969181788bf543ed4bd48f57

There's a few other regressions I've introduced that I plan to fix on Tuesday.

Thanks!

**Comment by fengb** [comment]
Should be fully working now: cf6e15c6708dbf8e3c3bb7c71816308de1038b06
